import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';

const $=id=>document.getElementById(id), clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n));
let S=JSON.parse(localStorage.getItem('eurolife-life')||'null')||{name:'Alex',money:1200,day:1,hour:8,hunger:72,energy:82,hygiene:78,fun:65,social:55,mood:70,job:'Café barista',home:'Montmartre Apartment',friends:{Amélie:20,Luca:5}};
const save=()=>localStorage.setItem('eurolife-life',JSON.stringify(S)), money=n=>'€'+Math.max(0,Math.round(n)).toLocaleString();
function ui(){['hunger','energy','hygiene','fun','social'].forEach(k=>{$(k).textContent=Math.round(S[k]);$(k+'Fill').style.width=S[k]+'%'});$('money').textContent=money(S.money);$('day').textContent=S.day}
const toast=t=>{$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>$('toast').classList.remove('show'),2100)};
const modal=html=>{$('sheet').innerHTML=html;$('modal').classList.add('show')}, close=()=>$('modal').classList.remove('show');$('modal').onclick=e=>{if(e.target.id==='modal')close()};

const scene=new THREE.Scene();scene.background=new THREE.Color(0x9dbed0);scene.fog=new THREE.Fog(0x9dbed0,45,115);
const camera=new THREE.OrthographicCamera(-14,14,10,-10,.1,160);camera.position.set(20,25,20);camera.lookAt(0,0,0);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;$('game').appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xe7f3ff,0x45515c,2));const sun=new THREE.DirectionalLight(0xffe9c2,3.2);sun.position.set(-25,40,15);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun);
const M=c=>new THREE.MeshStandardMaterial({color:c,roughness:.82}), ground=M(0xb9b3a8), road=M(0x30363d), wall=M(0xd8c2a5), wall2=M(0xb88470), roof=M(0x454b55), glass=M(0x385f78), dark=M(0x20272e), green=M(0x4d7a5a), gold=M(0xd5a93d);
const box=(w,h,d,m,x,y,z)=>{let o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;scene.add(o);return o};
function tree(x,z){box(.28,2,.28,dark,x,1,z);let a=new THREE.Mesh(new THREE.DodecahedronGeometry(1.25,0),green);a.position.set(x,3,z);a.castShadow=true;scene.add(a)}
function building(x,z,w,d,h,m,name){box(w,h,d,m,x,h/2,z);box(w+.08,.18,d+.08,roof,x,h+.08,z);for(let xx=x-w/2+1.1;xx<x+w/2;xx+=1.45)for(let y=1.5;y<h-1;y+=2.05)box(.55,.55,.035,glass,xx,y,z-d/2-.04);labels.push({name,x,z,w,d})}
const labels=[];box(90,.3,90,ground,0,-.15,0);
for(let x=-40;x<=40;x+=18)box(5,.08,90,road,x,-.01,0);for(let z=-40;z<=40;z+=18)box(90,.08,5,road,0,-.01,z);
building(-30,-30,12,11,9,wall,'Apartment');building(-14,-30,12,11,12,wall2,'Haussmann House');building(30,-30,12,11,10,wall,'Hotel');building(30,-14,12,11,13,wall2,'Office');building(-30,30,12,11,11,wall2,'Bakery');building(-14,30,12,11,8,wall,'Market');building(30,30,12,11,10,wall,'Cinema');
[[-10,-10],[-10,10],[10,-10],[10,10],[-27,-8],[-27,9],[27,-8],[27,9]].forEach(p=>tree(...p));
function sign(t,x,z){let c=document.createElement('canvas');c.width=600;c.height=130;let q=c.getContext('2d');q.fillStyle='#172534';q.fillRect(0,0,600,130);q.fillStyle='#fff';q.font='bold 48px sans-serif';q.textAlign='center';q.fillText(t,300,82);let s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c)}));s.scale.set(5.5,1.2,1);s.position.set(x,5,z);scene.add(s)}
sign('CAFÉ DES ARTISTES',-8,-8);sign('METRO · ABBESSES',8,8);sign('MARKET',-8,26);sign('CINÉMA',30,30);
function car(x,z,c){box(2.5,.65,.95,M(c),x,.42,z);box(1.1,.42,.8,M(c),x,.82,z);[-.75,.75].forEach(dx=>[-.43,.43].forEach(dz=>{let w=new THREE.Mesh(new THREE.CylinderGeometry(.18,.18,.12,10),dark);w.rotation.z=Math.PI/2;w.position.set(x+dx,.25,z+dz);scene.add(w)}))}
car(-7,-2,0x7d3f45);car(7,-2,0x3d6177);car(2,25,0xd0a63b);

const player=new THREE.Group();player.position.set(0,0,0);scene.add(player);const body=new THREE.Mesh(new THREE.CapsuleGeometry(.42,1.0,5,10),M(0x385f83));body.position.y=1.05;player.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.42,14,10),M(0xb87b58));head.position.y=1.9;player.add(head);const hair=new THREE.Mesh(new THREE.SphereGeometry(.44,14,8,0,Math.PI*2,0,Math.PI*.48),M(0x2a211e));hair.position.y=2.03;player.add(hair);
const npcs=[];function npc(name,x,z,c){let g=new THREE.Group();g.position.set(x,0,z);let b=new THREE.Mesh(new THREE.CapsuleGeometry(.36,.85,4,8),M(c));b.position.y=.9;g.add(b);let h=new THREE.Mesh(new THREE.SphereGeometry(.35,12,8),M(0xc58a69));h.position.y=1.62;g.add(h);scene.add(g);npcs.push({name,g,x,z,t:Math.random()*7})}
npc('Amélie',-3,-9,0xa35b74);npc('Luca',-7,5,0x6c5a94);npc('Noah',5,-8,0x4d7965);npc('Mila',7,7,0x9c7040);npc('Sofia',-20,0,0x52769a);

let near=null, mode='city', interactRadius=3.2;
const points=[{name:'Café des Artistes',x:-8,z:-8,fn:()=>work()},{name:'Your Apartment',x:-8,z:8,fn:()=>home()},{name:'Metro Abbesses',x:8,z:8,fn:()=>map()},{name:'Amélie',x:-3,z:-9,fn:()=>meet('Amélie')},{name:'Luca',x:-7,z:5,fn:()=>meet('Luca')}];
function clock(){return String(Math.floor(S.hour)).padStart(2,'0')+':'+String(Math.floor((S.hour%1)*60)).padStart(2,'0')}
function advance(h){S.hour+=h;while(S.hour>=24){S.hour-=24;S.day++}S.hunger=clamp(S.hunger-h*2);S.energy=clamp(S.energy-h*1.4);S.hygiene=clamp(S.hygiene-h*1.2);S.fun=clamp(S.fun-h*.5);S.social=clamp(S.social-h*.4);save();ui()}
function work(){if(S.energy<25)return toast('You need more energy for work.');advance(3);let pay=110+Math.floor(Math.random()*70);S.money+=pay;S.fun=clamp(S.fun-5);toast('Shift finished · +'+money(pay)+' · '+clock())}
function eat(){if(S.money<12)return toast('You need €12.');S.money-=12;S.hunger=clamp(S.hunger+28);S.energy=clamp(S.energy+5);S.mood=clamp(S.mood+4);save();ui();toast('Croissant + coffee · €12')}
function shower(){advance(.5);S.hygiene=100;S.fun=clamp(S.fun+3);toast('Fresh and clean.')}
function sleep(){S.hour=8;S.day++;S.energy=100;S.hunger=clamp(S.hunger-15);S.hygiene=clamp(S.hygiene-12);S.fun=clamp(S.fun+15);save();ui();toast('Good morning, '+S.name+' · Day '+S.day)}
function meet(n){S.social=clamp(S.social+16);S.fun=clamp(S.fun+9);S.energy=clamp(S.energy-4);S.friends[n]=clamp((S.friends[n]||0)+12);save();ui();toast(n+' liked spending time with you ❤️')}
function home(){mode='home';player.position.set(0,0,0);$('zone').textContent='HOME';$('place').textContent='Your Montmartre apartment';buildHome();toast('Home · tap furniture to interact')}
function buildHome(){scene.children.filter(o=>o.userData.home).forEach(o=>scene.remove(o));let floor=box(22,.25,18,M(0x806653),0,-.1,0);floor.userData.home=true;[[ -7,-5,5,4],[0,-5,8,4],[7,-5,5,4],[-7,4,5,5],[0,4,8,5],[7,4,5,5]].forEach(([x,z,w,d])=>{let q=box(w,.15,d,M(0xb99a7b),x,.03,z);q.userData.home=true});[['BED',-7,4],['BATH',7,4],['KITCHEN',0,-5],['LIVING',0,4],['DESK',7,-5]].forEach(([t,x,z])=>{let q=box(2,.8,1.2,M(t==='BED'?0x5f4562:t==='KITCHEN'?0x68705c:0x4b5865),x,.4,z);q.userData.home=true;q.userData.label=t});pointsHome=[{name:'Bed',x:-7,z:4,fn:sleep},{name:'Shower',x:7,z:4,fn:shower},{name:'Kitchen',x:0,z:-5,fn:eat},{name:'TV',x:0,z:4,fn:()=>{S.fun=clamp(S.fun+20);advance(1);toast('You watched TV.')}}]}
let pointsHome=[];
function city(){mode='city';scene.children.filter(o=>o.userData.home).forEach(o=>scene.remove(o));player.position.set(0,0,0);$('zone').textContent='MONTMARTRE';$('place').textContent='Paris · France';toast('Back in the city')}
function map(){modal('<h2>🗺️ Europe</h2><p>Your life starts in Paris. Cities unlock as your career and savings grow.</p><div class="grid"><div class="card"><b>🇫🇷 Paris</b><small>OPEN · Montmartre, cafés, metro, jobs</small></div><div class="card"><b>🇬🇧 London</b><small>COMING · rent, Underground, finance</small></div><div class="card"><b>🇳🇱 Amsterdam</b><small>COMING · bikes, canals, tech</small></div><div class="card"><b>🇩🇪 Berlin</b><small>COMING · nightlife, startups</small></div><div class="card"><b>🇮🇹 Rome</b><small>COMING · food, tourism, history</small></div><div class="card"><b>🇪🇸 Madrid</b><small>COMING · culture, sport, nightlife</small></div></div><button class="action primary wide" onclick="close()">RETURN TO PARIS</button>')}
function phone(){modal('<h2>📱 Your phone</h2><p>Life is managed through your phone, just like a modern social simulation.</p><div class="grid"><div class="card" onclick="jobApp()"><b>💼 Jobs</b><small>Find work and improve your income.</small></div><div class="card" onclick="map()"><b>🗺️ Europe</b><small>Travel and unlock cities.</small></div><div class="card"><b>🏠 Housing</b><small>'+S.home+' · Rent due weekly.</small></div><div class="card"><b>🏦 Bank</b><small>Balance '+money(S.money)+'.</small></div><div class="card"><b>🛍️ Shop</b><small>Clothes, furniture and upgrades.</small></div><div class="card"><b>💬 Messages</b><small>Amélie sent: “Coffee later?”</small></div></div>')}
function jobApp(){modal('<h2>💼 Jobs</h2><p>Choose a career. Better skills unlock higher-paying work.</p><div class="card"><b>☕ Café Barista · €110–€180</b><small>3-hour shift · Montmartre · beginner friendly</small></div><div class="card"><b>🧑‍💻 Junior Developer · €240–€420</b><small>4-hour shift · unlocks after skill progression</small></div><div class="card"><b>🚕 Driver · €150–€260</b><small>3-hour shift · requires transport</small></div><button class="action primary wide" onclick="close();work()">WORK CURRENT JOB</button>')}
function social(){modal('<h2>❤️ Social life</h2><p>Amélie '+S.friends.Amélie+'% · Luca '+S.friends.Luca+'% · Noah '+(S.friends.Noah||0)+'%</p><p>Meet people in the world, build friendships and eventually date, move in together or create a family.</p>')}
function creator(){modal('<h2>Build your character</h2><p>Make a new European life.</p><label>Name</label><input id="nameInput" value="'+S.name+'"><div class="grid"><button class="action" onclick="toast('Style presets coming with the clothing system')">👤 Appearance</button><button class="action" onclick="toast('Traits: Ambitious · Social · Creative')">⭐ Traits</button></div><button class="action primary wide" onclick="S.name=document.getElementById('nameInput').value||'Alex';save();close();toast('Welcome to Paris, '+S.name+'!')">START LIFE</button>')}
window.close=close;window.jobApp=jobApp;
$('home').onclick=()=>mode==='home'?city():home();$('phone').onclick=phone;$('phoneFloat').onclick=phone;$('map').onclick=map;$('job').onclick=jobApp;$('eat').onclick=eat;$('socialBtn').onclick=social;
const keys={},joy={x:0,y:0,on:false};addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=1;if(e.key.toLowerCase()==='e')interact()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=0);
const pad=$('joystick'),knob=$('knob');function jm(e){let r=pad.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),l=Math.hypot(dx,dy),m=42;if(l>m){dx=dx/l*m;dy=dy/l*m}joy.x=dx/m;joy.y=dy/m;knob.style.transform='translate('+dx+'px,'+dy+'px)'}pad.onpointerdown=e=>{joy.on=true;pad.setPointerCapture(e.pointerId);jm(e)};pad.onpointermove=e=>joy.on&&jm(e);pad.onpointerup=()=>{joy.on=false;joy.x=joy.y=0;knob.style.transform='translate(0,0)'};
function interact(){let list=mode==='home'?pointsHome:points;near=list.reduce((a,p)=>{let d=Math.hypot(player.position.x-p.x,player.position.z-p.z);return d<a.d?{p,d}:a},{p:null,d:99});if(near.d<interactRadius)near.p.fn();else toast('Walk closer to something interesting.')}
function loop(t){let dt=Math.min(.04,(t-(loop.last||t))/1000);loop.last=t;let mx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0)+joy.x,mz=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0)+joy.y,l=Math.hypot(mx,mz);if(l>1){mx/=l;mz/=l}if(l>.05){player.position.x+=mx*5*dt;player.position.z+=mz*5*dt;advance(dt*.15)}player.position.x=clamp(player.position.x,-39,39);player.position.z=clamp(player.position.z,-39,39);near=null;let list=mode==='home'?pointsHome:points,best=3;list.forEach(p=>{let d=Math.hypot(player.position.x-p.x,player.position.z-p.z);if(d<best){best=d;near=p}});$('hint').classList.toggle('show',!!near);if(near)$('hint').textContent='E · '+near.name;npcs.forEach(n=>{if(mode==='city'){n.t+=dt*.7;n.g.position.x=n.x+Math.sin(n.t)*2.4;n.g.position.z=n.z+Math.cos(n.t*.8)*2.1}else n.g.visible=false});if(mode==='city')npcs.forEach(n=>n.g.visible=true);let target=new THREE.Vector3(player.position.x,0,player.position.z);camera.position.lerp(new THREE.Vector3(target.x+20,25,target.z+20),.08);camera.lookAt(target);renderer.render(scene,camera);requestAnimationFrame(loop)}
ui();if(!localStorage.getItem('eurolife-life-seen')){localStorage.setItem('eurolife-life-seen','1');setTimeout(creator,500)}requestAnimationFrame(loop);addEventListener('resize',()=>{let a=innerWidth/innerHeight,c=10*a;camera.left=-c;camera.right=c;camera.top=10;camera.bottom=-10;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
